In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv('G:\Workshop\Al-ML\salary.csv')

<>:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
<>:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
C:\Users\M M\AppData\Local\Temp\ipykernel_9700\2570350896.py:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
  dataset = pd.read_csv('G:\Workshop\Al-ML\salary.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   education.num   32561 non-null  int64
 2   capital.gain    32561 non-null  int64
 3   hours.per.week  32561 non-null  int64
 4   income          32561 non-null  object
dtypes: int64(4), object(1)
memory usage: 1.2+ MB

In [4]:
dataset.isna().sum()

age               0
education.num     0
capital.gain      0
hours.per.week    0
income            0
dtype: int64

In [5]:
dataset

       age  education.num  capital.gain  hours.per.week income
0       90              9             0              40  <=50K
1       82              9             0              18  <=50K
2       66             10             0              40  <=50K
3       54              4             0              40  <=50K
4       41             10             0              40  <=50K
...    ...            ...           ...             ...    ...
32556   22             10             0              40  <=50K
32557   27             12             0              38  <=50K
32558   40              9             0              40   >50K
32559   58              9             0              40  <=50K
32560   22              9             0              20  <=50K

[32561 rows x 5 columns]

In [6]:
dataset.columns

Index(['age', 'education.num', 'capital.gain', 'hours.per.week', 'income'], dtype='object')

In [7]:
dataset.head()

   age  education.num  capital.gain  hours.per.week income
0   90              9             0              40  <=50K
1   82              9             0              18  <=50K
2   66             10             0              40  <=50K
3   54              4             0              40  <=50K
4   41             10             0              40  <=50K

In [8]:
dataset.head(10)

   age  education.num  capital.gain  hours.per.week income
0   90              9             0              40  <=50K
1   82              9             0              18  <=50K
2   66             10             0              40  <=50K
3   54              4             0              40  <=50K
4   41             10             0              40  <=50K
5   34              9             0              45  <=50K
6   38              6             0              40  <=50K
7   74             16             0              20   >50K
8   68              9             0              40  <=50K
9   41             10             0              60   >50K

In [9]:
dataset.head(101)

     age  education.num  capital.gain  hours.per.week income
0     90              9             0              40  <=50K
1     82              9             0              18  <=50K
2     66             10             0              40  <=50K
3     54              4             0              40  <=50K
4     41             10             0              40  <=50K
..   ...            ...           ...             ...    ...
96    46             15             0              80   >50K
97    39             11             0              40   >50K
98    39             15             0              99   >50K
99    59             16             0              45   >50K
100   50             15             0              60   >50K

[101 rows x 5 columns]

In [10]:
dataset.iloc[101:201]

     age  education.num  capital.gain  hours.per.week income
101   46             16             0              55   >50K
102   53             13             0              40   >50K
103   50             15             0              30   >50K
104   41             15             0              55   >50K
105   36             13             0              45   >50K
..   ...            ...           ...             ...    ...
196   23             13             0              40   >50K
197   49              5             0              40   >50K
198   27             10             0              40   >50K
199   90              9             0              40  <=50K
200   68              9             0              30  <=50K

[100 rows x 5 columns]